/* Generated By:JJTree: Do not edit this line. ASTEvaluation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEvaluation extends SimpleNode {
  public ASTEvaluation(int id) {
    super(id);
  }

  public ASTEvaluation(SimpL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpLVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a76fea87a2a5dc7b7063a54eb9f39a88 (do not edit this line) */
