/* Generated By:JJTree: Do not edit this line. ASTfragment.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfragment extends SimpleNode {
  public ASTfragment(int id) {
    super(id);
  }

  public ASTfragment(SimpL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5ba7df2ecf539b11e49f852c7662e772 (do not edit this line) */
