/* Generated By:JJTree: Do not edit this line. ASTparam_list.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparam_list extends SimpleNode {
  public ASTparam_list(int id) {
    super(id);
  }

  public ASTparam_list(SimpL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpLVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=373aa94f2a3f876de62a3a87043ca5d0 (do not edit this line) */
