/* Generated By:JJTree: Do not edit this line. ASTRETURNVALUE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRETURNVALUE extends SimpleNode {
  public ASTRETURNVALUE(int id) {
    super(id);
  }

  public ASTRETURNVALUE(SimpL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpLVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1f3c3e28e7fe6247f34b0443162bbda2 (do not edit this line) */
