/* Generated By:JJTree: Do not edit this line. ASTvar_decl.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvar_decl extends SimpleNode {
  public ASTvar_decl(int id) {
    super(id);
  }

  public ASTvar_decl(SimpL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpLVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1566d54a76da8969405046be7d557ee3 (do not edit this line) */
