/* Generated By:JavaCC: Do not edit this line. SimpLVisitor.java Version 6.0_1 */
public interface SimpLVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTConstDecl node, Object data);
  public Object visit(ASTFunctionDecl node, Object data);
  public Object visit(ASTFunctionBody node, Object data);
  public Object visit(ASTParamList node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTMain node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTFunctionCall node, Object data);
  public Object visit(ASTAddExpr node, Object data);
  public Object visit(ASTSubExpr node, Object data);
  public Object visit(ASTMultExpr node, Object data);
  public Object visit(ASTDivExpr node, Object data);
  public Object visit(ASTModExpr node, Object data);
  public Object visit(ASTIdentList node, Object data);
  public Object visit(ASTArgList node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTIdentifier node, Object data);
}
/* JavaCC - OriginalChecksum=473a34fe4fd201b2c260dbe3fe3d09b9 (do not edit this line) */
