/* Generated By:JavaCC: Do not edit this line. SimpLTreeConstants.java Version 6.0_1 */
public interface SimpLTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVARDECL = 2;
  public int JJTCONSTDECL = 3;
  public int JJTFUNCTIONDECL = 4;
  public int JJTFUNCTIONBODY = 5;
  public int JJTPARAMLIST = 6;
  public int JJTTYPE = 7;
  public int JJTMAIN = 8;
  public int JJTASSIGNMENT = 9;
  public int JJTFUNCTIONCALL = 10;
  public int JJTADDEXPR = 11;
  public int JJTSUBEXPR = 12;
  public int JJTMULTEXPR = 13;
  public int JJTDIVEXPR = 14;
  public int JJTMODEXPR = 15;
  public int JJTIDENTLIST = 16;
  public int JJTARGLIST = 17;
  public int JJTNUMBER = 18;
  public int JJTIDENTIFIER = 19;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "VarDecl",
    "ConstDecl",
    "FunctionDecl",
    "FunctionBody",
    "ParamList",
    "Type",
    "Main",
    "Assignment",
    "FunctionCall",
    "AddExpr",
    "SubExpr",
    "MultExpr",
    "DivExpr",
    "ModExpr",
    "IdentList",
    "ArgList",
    "Number",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=38fd52772775f651ecddf3f6c1438798 (do not edit this line) */
