/* Generated By:JavaCC: Do not edit this line. SimpLDefaultVisitor.java Version 6.0_1 */
public class SimpLDefaultVisitor implements SimpLVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprogram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvar_decl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTconst_decl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTparam_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTexpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnumber node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTidentifier node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=0ad6c6cfb50669789be9abd12db99bdd (do not edit this line) */
