/* Generated By:JavaCC: Do not edit this line. SimpLDefaultVisitor.java Version 6.0_1 */
public class SimpLDefaultVisitor implements SimpLVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarDecl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTConstDecl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionDecl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionBody node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParamList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTType node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMain node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssignment node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionCall node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAddExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSubExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMultExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDivExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTModExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArgList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNumber node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentifier node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=efaf9211f25d66680e26b74dc6e317ad (do not edit this line) */
